cacheFolder: .yarn/cache

checksumBehavior: update

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

logFilters:
  - code: YN0076
    level: discard
  - code: YN0000
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs
