cacheFolder: .yarn/cache

nodeLinker: node-modules

logFilters:
  - code: YN0076
    level: discard
  - code: YN0000
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
