[build]
  command = "yarn build"
  publish = "dist/"

  [build.environment]
    PYTHON_VERSION = "3.7"
    # Match version in monorepo root .yarnrc.yml
    YARN_VERSION = "3.1.1"
    NETLIFY_USE_YARN = "true"
    NETLIFY_YARN_WORKSPACES = "true"
    YARN_ENABLE_GLOBAL_CACHE = "true"
    YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"
    CYPRESS_INSTALL_BINARY = "0"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "0"
