[build]
  command = "yarn build"
  publish = "dist/"

  [build.environment]
    PYTHON_VERSION = "3.7"
    # Match yarn version in monorepo root .yarnrc.yml
    YARN_VERSION = "3.1.1"
    NETLIFY_USE_YARN = "true"
    YARN_ENABLE_GLOBAL_CACHE = "true"
    YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"
