[build]
  command = "yarn build"
  publish = "dist/"

  [build.environment]
    PYTHON_VERSION = "3.7"
    # Match yarn version in monorepo root .yarnrc.yml
    NETLIFY_USE_YARN = "true"
    YARN_VERSION = "3.1.1"
