name: Build website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'packages/studio/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Debug
        run: yarn versions

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build Website
        run: yarn workspace @sallypayne/web build
        env:
          MINIFIED: true
          SITE_URL: 'https://www.sallypayne.com'
          SANITY_STUDIO_API_PROJECT_ID: 's9bzuqxn'
          SANITY_STUDIO_API_DATASET: 'prod'
          SANITY_STUDIO_API_VERSION: '2021-08-13'
          SANITY_STUDIO_API_TOKEN: ${{ secrets.SANITY_STUDIO_API_TOKEN }}
          ETSY_STORE_ID: '19320819'
          ETSY_API_TOKEN: ${{ secrets.ETSY_API_TOKEN }}
