name: Build website

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Yarn
      run: npm install -g yarn
    - uses: actions/checkout@v2
    - name: Run install and build
      with:
        node-version: '14.x'
        cache: 'npm'
      uses: actions/setup-node@v2
      env:
        MINIFIED: true
        SITE_URL: 'https://www.sallypayne.com'
        SANITY_STUDIO_API_PROJECT_ID: 's9bzuqxn'
        SANITY_STUDIO_API_DATASET: 'prod'
        SANITY_STUDIO_API_VERSION: '2021-08-13'
        SANITY_STUDIO_API_TOKEN: ${{ secrets.SANITY_STUDIO_API_TOKEN }}
        ETSY_STORE_ID: '19320819'
        ETSY_API_TOKEN: ${{ secrets.ETSY_API_TOKEN }}
    - run: yarn install
    - run: yarn workspace @sallypayne/web build
