name: Build website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'packages/studio/**'

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build Website
        run: yarn workspace @sallypayne/web build
        env:
          MINIFIED_CSS: true
          PUBLIC_SITE_URL: 'https://www.sallypayne.com'
          PUBLIC_SANITY_STUDIO_API_PROJECT_ID: 's9bzuqxn'
          PUBLIC_SANITY_STUDIO_API_DATASET: 'prod'
          PUBLIC_SANITY_STUDIO_API_VERSION: '2021-08-13'
          PUBLIC_SANITY_STUDIO_API_TOKEN: ${{ secrets.SANITY_STUDIO_API_TOKEN }}
          PUBLIC_ETSY_STORE_ID: '19320819'
          PUBLIC_ETSY_API_TOKEN: ${{ secrets.ETSY_API_TOKEN }}
