name: Build website
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run install
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and Bootstrap dependencies
        run: |
          cd packages/web
          npm install

      - name: Build
        run: npm run build
        env:
          MINIFIED: true
          SITE_URL: 'https://www.sallypayne.com'
          SANITY_STUDIO_API_PROJECT_ID: 's9bzuqxn'
          SANITY_STUDIO_API_DATASET: 'prod'
          SANITY_STUDIO_API_VERSION: '2021-08-13'
          SANITY_STUDIO_API_TOKEN: ${{ secrets.SANITY_STUDIO_API_TOKEN }}
          ETSY_STORE_ID: 19320819
          ETSY_API_TOKEN: ${{ secrets.ETSY_API_TOKEN }}
