name: Studio

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'apps/web/**'

env:
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm --filter @sallypayne/studio types:check

      - name: Build studio
        run: pnpm --filter @sallypayne/studio build
