name: Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'apps/studio/**'

env:
  MINIFIED_CSS: true
  PUBLIC_SITE_URL: 'https://www.sallypayne.com'
  PUBLIC_SANITY_STUDIO_API_PROJECT_ID: 's9bzuqxn'
  PUBLIC_SANITY_STUDIO_API_DATASET: 'prod'
  PUBLIC_SANITY_STUDIO_API_VERSION: '2025-02-19'
  PUBLIC_SANITY_STUDIO_API_TOKEN: ${{ secrets.SANITY_STUDIO_API_TOKEN }}
  PUBLIC_ETSY_STORE_ID: '19320819'
  PUBLIC_ETSY_API_TOKEN: ${{ secrets.ETSY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm --filter @sallypayne/web types:check

      - name: Build website
        run: pnpm --filter @sallypayne/web build
